"""Brand dictionary for the creator scan: names creators actually say on camera, grouped by category.

Each entry: (name, category, aliases, handles). Aliases are alternate spellings and speech-to-text forms; handles
are the brand's own @accounts (Instagram/TikTok share most of them). ambiguous() lists names that are also ordinary
words, so a spoken-only match needs a context word before it counts.

Hand-curated. Grow it from "brand missing" reports; swap for an entity model when precision bites.
"""

BRANDS = [
    # Beauty and skincare
    ("Sephora", "beauty", [], ["sephora", "sephoramiddleeast"]),
    ("Huda Beauty", "beauty", ["Huda"], ["hudabeauty"]),
    ("Rare Beauty", "beauty", [], ["rarebeauty"]),
    ("Fenty Beauty", "beauty", ["Fenty"], ["fentybeauty"]),
    ("Charlotte Tilbury", "beauty", [], ["charlottetilbury"]),
    ("Glossier", "beauty", [], ["glossier"]),
    ("MAC Cosmetics", "beauty", ["MAC"], ["maccosmetics"]),
    ("NYX", "beauty", ["NYX Cosmetics"], ["nyxcosmetics"]),
    ("Maybelline", "beauty", [], ["maybelline"]),
    ("L'Oreal", "beauty", ["Loreal", "L'Oréal"], ["lorealparis"]),
    ("Dior Beauty", "beauty", ["Dior"], ["diorbeauty"]),
    ("Kylie Cosmetics", "beauty", [], ["kyliecosmetics"]),
    ("e.l.f.", "beauty", ["elf cosmetics", "e l f"], ["elfcosmetics"]),
    ("Benefit Cosmetics", "beauty", ["Benefit"], ["benefitcosmetics"]),
    ("Anastasia Beverly Hills", "beauty", ["ABH"], ["anastasiabeverlyhills"]),
    ("Too Faced", "beauty", [], ["toofaced"]),
    ("Tarte", "beauty", ["Tarte Cosmetics"], ["tartecosmetics"]),
    ("Urban Decay", "beauty", [], ["urbandecay"]),
    ("Milk Makeup", "beauty", [], ["milkmakeup"]),
    ("Patrick Ta", "beauty", [], ["patrickta"]),
    ("Makeup by Mario", "beauty", [], ["makeupbymario"]),
    ("Sol de Janeiro", "beauty", [], ["soldejaneiro"]),
    ("Bath & Body Works", "beauty", ["Bath and Body Works"], ["bathandbodyworks"]),
    ("Olaplex", "beauty", [], ["olaplex"]),
    ("Dyson", "tech", ["Dyson Airwrap", "Airwrap"], ["dyson", "dysonhair"]),
    ("Shark Beauty", "tech", ["Shark FlexStyle", "FlexStyle"], ["sharkbeauty"]),
    ("ghd", "beauty", [], ["ghdhair"]),
    ("K18", "beauty", [], ["k18hair"]),
    ("Kerastase", "beauty", ["Kérastase"], ["kerastase_official"]),
    ("Moroccanoil", "beauty", ["Moroccan oil"], ["moroccanoil"]),
    ("Ouai", "beauty", [], ["theouai"]),
    ("Gisou", "beauty", [], ["gisou"]),
    ("Mielle", "beauty", ["Mielle Organics"], ["mielleorganics"]),
    ("CeraVe", "skincare", ["Cera Ve"], ["cerave"]),
    ("The Ordinary", "skincare", [], ["theordinary"]),
    ("La Roche-Posay", "skincare", ["La Roche Posay"], ["larocheposay"]),
    ("Drunk Elephant", "skincare", [], ["drunkelephant"]),
    ("Glow Recipe", "skincare", [], ["glowrecipe"]),
    ("Paula's Choice", "skincare", ["Paulas Choice"], ["paulaschoice"]),
    ("Tatcha", "skincare", [], ["tatcha"]),
    ("Summer Fridays", "skincare", [], ["summerfridays"]),
    ("Laneige", "skincare", [], ["laneige_us", "laneige"]),
    ("COSRX", "skincare", ["Cosrx"], ["cosrx"]),
    ("Beauty of Joseon", "skincare", [], ["beautyofjoseon_official"]),
    ("Medicube", "skincare", [], ["medicube_us", "medicube"]),
    ("Anua", "skincare", [], ["anua_global"]),
    ("Byoma", "skincare", [], ["byoma"]),
    ("Bubble Skincare", "skincare", ["Bubble"], ["bubble"]),
    ("Kiehl's", "skincare", ["Kiehls"], ["kiehls"]),
    ("Neutrogena", "skincare", [], ["neutrogena"]),
    ("Cetaphil", "skincare", [], ["cetaphil"]),
    ("Bioderma", "skincare", [], ["bioderma"]),
    ("Supergoop", "skincare", [], ["supergoop"]),
    ("Rhode", "skincare", ["Rhode Skin"], ["rhode"]),
    ("Nivea", "skincare", [], ["nivea"]),
    ("Dove", "skincare", [], ["dove"]),
    ("Vaseline", "skincare", [], ["vaseline"]),
    # Fashion, footwear and accessories
    ("Nike", "fashion", [], ["nike"]),
    ("Adidas", "fashion", [], ["adidas"]),
    ("New Balance", "fashion", [], ["newbalance"]),
    ("Puma", "fashion", [], ["puma"]),
    ("Zara", "fashion", [], ["zara"]),
    ("H&M", "fashion", ["H and M"], ["hm"]),
    ("Shein", "fashion", [], ["shein_official", "shein"]),
    ("Uniqlo", "fashion", [], ["uniqlo"]),
    ("Lululemon", "fashion", [], ["lululemon"]),
    ("Alo Yoga", "fashion", ["Alo"], ["alo", "aloyoga"]),
    ("Gymshark", "fashion", ["Gym shark"], ["gymshark"]),
    ("Skims", "fashion", [], ["skims"]),
    ("Aritzia", "fashion", [], ["aritzia"]),
    ("Abercrombie", "fashion", ["Abercrombie & Fitch"], ["abercrombie"]),
    ("Princess Polly", "fashion", [], ["princesspolly"]),
    ("Revolve", "fashion", [], ["revolve"]),
    ("ASOS", "fashion", [], ["asos"]),
    ("Namshi", "fashion", [], ["namshi"]),
    ("Ounass", "fashion", [], ["ounass"]),
    ("Farfetch", "fashion", [], ["farfetch"]),
    ("Louis Vuitton", "luxury", [], ["louisvuitton"]),
    ("Gucci", "luxury", [], ["gucci"]),
    ("Prada", "luxury", [], ["prada"]),
    ("Chanel", "luxury", [], ["chanelofficial", "chanel"]),
    ("Hermes", "luxury", ["Hermès"], ["hermes"]),
    ("Miu Miu", "luxury", [], ["miumiu"]),
    ("Loewe", "luxury", [], ["loewe"]),
    ("Balenciaga", "luxury", [], ["balenciaga"]),
    ("Coach", "fashion", [], ["coach"]),
    ("Michael Kors", "fashion", [], ["michaelkors"]),
    ("Ray-Ban", "fashion", ["Ray Ban", "Rayban"], ["rayban"]),
    ("Crocs", "fashion", [], ["crocs"]),
    ("Birkenstock", "fashion", [], ["birkenstock"]),
    ("Ugg", "fashion", ["Uggs"], ["ugg"]),
    ("On Running", "fashion", ["On Cloud", "On Clouds"], ["on_running", "on"]),
    ("Hoka", "fashion", ["Hokas"], ["hoka"]),
    ("Pandora", "fashion", [], ["theofficialpandora"]),
    ("Swarovski", "fashion", [], ["swarovski"]),
    ("Daniel Wellington", "fashion", [], ["danielwellington"]),
    # Food, snacks and grocery
    ("Tim Hortons", "food", ["Timmies", "Tim Horton's"], ["timhortons", "timhortonsgcc"]),
    ("Starbucks", "coffee", [], ["starbucks", "starbucksuae"]),
    ("Dunkin", "coffee", ["Dunkin Donuts", "Dunkin'"], ["dunkin"]),
    ("Costa Coffee", "coffee", ["Costa"], ["costacoffee"]),
    ("Nespresso", "coffee", [], ["nespresso"]),
    ("Lavazza", "coffee", [], ["lavazza"]),
    ("McDonald's", "food", ["McDonalds", "Mcdonald", "Maccies", "Mickey D's"], ["mcdonalds", "mcdonaldsuae"]),
    ("KFC", "food", [], ["kfc", "kfcarabia"]),
    ("Burger King", "food", [], ["burgerking"]),
    ("Shake Shack", "food", [], ["shakeshack"]),
    ("Five Guys", "food", [], ["fiveguys"]),
    ("Chick-fil-A", "food", ["Chick fil A", "Chickfila"], ["chickfila"]),
    ("Chipotle", "food", [], ["chipotle"]),
    ("Domino's", "food", ["Dominos", "Domino's Pizza"], ["dominos"]),
    ("Papa John's", "food", ["Papa Johns"], ["papajohns"]),
    ("Subway", "food", [], ["subway"]),
    ("Taco Bell", "food", [], ["tacobell"]),
    ("Wendy's", "food", ["Wendys"], ["wendys"]),
    ("Popeyes", "food", [], ["popeyes"]),
    ("Pret", "food", ["Pret a Manger"], ["pret"]),
    ("Nando's", "food", ["Nandos"], ["nandosuk", "nandos"]),
    ("Al Baik", "food", ["Albaik"], ["albaik"]),
    ("Kinder", "food", ["Kinder Bueno"], ["kinder"]),
    ("Nutella", "food", [], ["nutella"]),
    ("Oreo", "food", ["Oreos"], ["oreo"]),
    ("KitKat", "food", ["Kit Kat"], ["kitkat"]),
    ("Pringles", "food", [], ["pringles"]),
    ("Doritos", "food", [], ["doritos"]),
    ("Lay's", "food", ["Lays"], ["lays"]),
    ("Cheetos", "food", [], ["cheetos"]),
    ("Ben & Jerry's", "food", ["Ben and Jerry's", "Ben and Jerrys"], ["benandjerrys"]),
    ("Magnum", "food", ["Magnum ice cream"], ["magnum"]),
    ("Haagen-Dazs", "food", ["Haagen Dazs", "Häagen-Dazs"], ["haagendazs"]),
    ("Lindt", "food", [], ["lindt"]),
    ("Ferrero Rocher", "food", ["Ferrero"], ["ferrerorocher"]),
    ("Galaxy Chocolate", "food", ["Galaxy bar"], ["galaxychocolate"]),
    ("Cadbury", "food", [], ["cadburyuk", "cadbury"]),
    ("Heinz", "food", [], ["heinz"]),
    ("Philadelphia", "food", ["Philadelphia cream cheese"], ["philadelphia"]),
    ("Almarai", "food", [], ["almarai"]),
    ("Al Rawabi", "food", [], ["alrawabi"]),
    ("Puck", "food", ["Puck cheese"], ["puckarabia"]),
    ("Lurpak", "food", [], ["lurpak"]),
    ("Kellogg's", "food", ["Kelloggs"], ["kelloggsus"]),
    ("Quaker", "food", ["Quaker Oats"], ["quaker"]),
    ("Chobani", "food", [], ["chobani"]),
    ("Oatly", "food", [], ["oatly"]),
    ("Alpro", "food", [], ["alpro"]),
    ("HelloFresh", "food", ["Hello Fresh"], ["hellofresh"]),
    ("Factor", "food", ["Factor meals", "Factor75"], ["factor_meals"]),
    ("Gousto", "food", [], ["goustocooking"]),
    ("Huel", "food", [], ["huel"]),
    # Beverages
    ("Coca-Cola", "beverage", ["Coca Cola", "Coke"], ["cocacola"]),
    ("Pepsi", "beverage", [], ["pepsi"]),
    ("Red Bull", "beverage", ["Redbull"], ["redbull"]),
    ("Monster Energy", "beverage", ["Monster"], ["monsterenergy"]),
    ("Celsius", "beverage", [], ["celsiusofficial"]),
    ("Prime Hydration", "beverage", ["Prime"], ["drinkprime"]),
    ("Gatorade", "beverage", [], ["gatorade"]),
    ("Liquid IV", "beverage", ["Liquid I.V."], ["liquidiv"]),
    ("Poppi", "beverage", [], ["drinkpoppi"]),
    ("Olipop", "beverage", [], ["drinkolipop"]),
    ("Al Ain Water", "beverage", ["Al Ain"], ["alainwater"]),
    ("Masafi", "beverage", [], ["masafi"]),
    ("Evian", "beverage", [], ["evian"]),
    ("Fiji Water", "beverage", ["Fiji"], ["fijiwater"]),
    ("Vimto", "beverage", [], ["vimto"]),
    ("Barbican", "beverage", [], ["barbican"]),
    ("Lipton", "beverage", [], ["lipton"]),
    ("Ahmad Tea", "beverage", [], ["ahmadtea"]),
    # Delivery, mobility and marketplaces
    ("Talabat", "apps", [], ["talabat"]),
    ("Deliveroo", "apps", [], ["deliveroo", "deliveroo_ae"]),
    ("Uber Eats", "apps", ["UberEats"], ["ubereats"]),
    ("DoorDash", "apps", ["Door Dash"], ["doordash"]),
    ("Careem", "apps", [], ["careem"]),
    ("Uber", "apps", [], ["uber"]),
    ("Noon", "retail", ["noon.com"], ["noon"]),
    ("Amazon", "retail", ["Amazon Prime", "amazon.ae"], ["amazon", "amazonae"]),
    ("Temu", "retail", [], ["temu"]),
    ("Instashop", "apps", [], ["instashopapp"]),
    ("Carrefour", "retail", [], ["carrefouruae", "carrefour"]),
    ("Lulu Hypermarket", "retail", ["Lulu"], ["luluhypermarket"]),
    ("IKEA", "home", [], ["ikea", "ikeauae"]),
    ("Home Centre", "home", [], ["homecentre"]),
    ("Pottery Barn", "home", [], ["potterybarn"]),
    ("West Elm", "home", [], ["westelm"]),
    ("Target", "retail", [], ["target"]),
    ("Walmart", "retail", [], ["walmart"]),
    ("Costco", "retail", [], ["costco"]),
    ("Trader Joe's", "retail", ["Trader Joes"], ["traderjoes"]),
    ("Whole Foods", "retail", [], ["wholefoods"]),
    ("Sainsbury's", "retail", ["Sainsburys"], ["sainsburys"]),
    ("Tesco", "retail", [], ["tesco"]),
    ("Marks & Spencer", "retail", ["Marks and Spencer", "M&S"], ["marksandspencer"]),
    ("Waitrose", "retail", [], ["waitrose"]),
    ("Spinneys", "retail", [], ["spinneysuae"]),
    ("Kibsons", "retail", [], ["kibsons"]),
    # Tech, devices and software
    ("Apple", "tech", ["iPhone", "MacBook", "AirPods", "Apple Watch", "iPad"], ["apple"]),
    ("Samsung", "tech", ["Galaxy phone", "Samsung Galaxy"], ["samsung", "samsunggulf"]),
    ("Google Pixel", "tech", ["Pixel"], ["googlepixel"]),
    ("Sony", "tech", [], ["sony"]),
    ("Bose", "tech", [], ["bose"]),
    ("Beats", "tech", ["Beats by Dre"], ["beatsbydre"]),
    ("JBL", "tech", [], ["jbl", "jblaudio"]),
    ("GoPro", "tech", [], ["gopro"]),
    ("DJI", "tech", ["DJI Osmo", "Osmo Pocket"], ["djiglobal"]),
    ("Insta360", "tech", [], ["insta360"]),
    ("Canon", "tech", [], ["canonusa", "canon"]),
    ("Logitech", "tech", [], ["logitech"]),
    ("Razer", "gaming", [], ["razer"]),
    ("Anker", "tech", [], ["anker_official"]),
    ("Ninja Kitchen", "home", ["Ninja Creami", "Ninja blender", "Ninja air fryer"], ["ninjakitchen"]),
    ("Philips", "home", ["Philips Airfryer"], ["philips"]),
    ("Instant Pot", "home", [], ["instantpot"]),
    ("Stanley", "home", ["Stanley cup", "Stanley tumbler"], ["stanley_brand"]),
    ("Owala", "home", [], ["owala"]),
    ("Yeti", "home", [], ["yeti"]),
    ("Canva", "software", [], ["canva"]),
    ("Notion", "software", [], ["notionhq"]),
    ("CapCut", "software", ["Cap Cut"], ["capcut"]),
    ("Adobe", "software", ["Photoshop", "Lightroom", "Premiere Pro"], ["adobe"]),
    ("Squarespace", "software", [], ["squarespace"]),
    ("Shopify", "software", [], ["shopify"]),
    ("NordVPN", "software", ["Nord VPN"], ["nordvpn"]),
    ("ExpressVPN", "software", ["Express VPN"], ["expressvpn"]),
    ("Surfshark", "software", [], ["surfshark"]),
    ("Grammarly", "software", [], ["grammarly"]),
    ("Duolingo", "software", [], ["duolingo"]),
    ("Spotify", "software", [], ["spotify"]),
    ("Audible", "software", [], ["audible"]),
    ("Skillshare", "software", [], ["skillshare"]),
    ("Brilliant", "software", ["Brilliant.org"], ["brilliantorg"]),
    ("BetterHelp", "software", ["Better Help"], ["betterhelp"]),
    ("Headspace", "software", [], ["headspace"]),
    ("Calm", "software", ["Calm app"], ["calm"]),
    ("Babbel", "software", [], ["babbel"]),
    ("Honey", "software", ["Honey extension"], ["honey"]),
    ("Raycon", "tech", ["Raycons"], ["raycon"]),
    ("Manscaped", "health", [], ["manscaped"]),
    ("Ridge Wallet", "fashion", ["Ridge"], ["ridge"]),
    ("Incogni", "software", [], ["incogni_official"]),
    ("Aura", "software", ["Aura app"], ["aura"]),
    # Finance and fintech
    ("Revolut", "finance", [], ["revolutapp"]),
    ("Wise", "finance", ["TransferWise"], ["wise"]),
    ("Monzo", "finance", [], ["monzo"]),
    ("Klarna", "finance", [], ["klarna"]),
    ("Tabby", "finance", [], ["tabby"]),
    ("Tamara", "finance", [], ["tamara"]),
    ("PayPal", "finance", [], ["paypal"]),
    ("Binance", "finance", [], ["binance"]),
    ("Coinbase", "finance", [], ["coinbase"]),
    ("eToro", "finance", [], ["etoro"]),
    ("Robinhood", "finance", [], ["robinhoodapp"]),
    ("American Express", "finance", ["Amex"], ["americanexpress"]),
    ("Emirates NBD", "finance", ["ENBD"], ["emiratesnbd"]),
    ("Liv Bank", "finance", ["Liv."], ["livdigitalbank"]),
    ("Wio", "finance", ["Wio Bank"], ["wiobank"]),
    # Travel and hospitality
    ("Emirates", "travel", ["Emirates Airline", "Fly Emirates"], ["emirates"]),
    ("Etihad", "travel", ["Etihad Airways"], ["etihad"]),
    ("Qatar Airways", "travel", [], ["qatarairways"]),
    ("flydubai", "travel", ["Fly Dubai"], ["flydubai"]),
    ("Air Arabia", "travel", [], ["airarabiagroup"]),
    ("Ryanair", "travel", [], ["ryanair"]),
    ("Booking.com", "travel", ["Booking"], ["bookingcom"]),
    ("Airbnb", "travel", [], ["airbnb"]),
    ("Expedia", "travel", [], ["expedia"]),
    ("Marriott", "travel", ["Marriott Bonvoy"], ["marriottbonvoy"]),
    ("Hilton", "travel", [], ["hilton"]),
    ("Atlantis The Palm", "travel", ["Atlantis Dubai", "Atlantis The Royal"], ["atlantisthepalm", "atlantistheroyal"]),
    ("Jumeirah", "travel", ["Burj Al Arab"], ["jumeirahgroup"]),
    ("Visit Dubai", "travel", [], ["visit.dubai", "visitdubai"]),
    ("Visit Qatar", "travel", [], ["visitqatar"]),
    ("Saudi Tourism", "travel", ["Visit Saudi"], ["visitsaudi"]),
    ("Klook", "travel", [], ["klook"]),
    ("GetYourGuide", "travel", ["Get Your Guide"], ["getyourguide"]),
    ("Holafly", "travel", [], ["holafly"]),
    ("Airalo", "travel", [], ["airalo"]),
    # Fitness, health and wellness
    ("Peloton", "fitness", [], ["onepeloton"]),
    ("Whoop", "fitness", [], ["whoop"]),
    ("Oura", "fitness", ["Oura ring"], ["ouraring"]),
    ("Garmin", "fitness", [], ["garmin"]),
    ("Fitbit", "fitness", [], ["fitbit"]),
    ("MyProtein", "fitness", ["My Protein"], ["myprotein"]),
    ("Optimum Nutrition", "fitness", [], ["optimumnutrition"]),
    ("Ghost Lifestyle", "fitness", ["Ghost energy", "Ghost protein"], ["ghostlifestyle"]),
    ("AG1", "fitness", ["Athletic Greens"], ["drinkag1"]),
    ("Bloom Nutrition", "fitness", ["Bloom greens"], ["bloomsupps"]),
    ("Ritual", "health", ["Ritual vitamins"], ["ritual"]),
    ("Hims", "health", [], ["hims"]),
    ("Hers", "health", ["forhers"], ["hers"]),
    ("Fitness First", "fitness", [], ["fitnessfirstme"]),
    ("Barry's", "fitness", ["Barrys", "Barry's Bootcamp"], ["barrys"]),
    ("ClassPass", "fitness", ["Class Pass"], ["classpass"]),
    ("Strava", "fitness", [], ["strava"]),
    ("Therabody", "health", ["Theragun"], ["therabody"]),
    ("Hydrow", "fitness", [], ["hydrow"]),
    # Gaming and entertainment
    ("PlayStation", "gaming", ["PS5", "PS4"], ["playstation"]),
    ("Xbox", "gaming", [], ["xbox"]),
    ("Nintendo", "gaming", ["Nintendo Switch"], ["nintendo"]),
    ("Steam", "gaming", ["Steam Deck"], ["steam"]),
    ("Roblox", "gaming", [], ["roblox"]),
    ("Fortnite", "gaming", [], ["fortnite"]),
    ("Raid Shadow Legends", "gaming", ["Raid"], ["raidshadowlegends"]),
    ("Genshin Impact", "gaming", ["Genshin"], ["genshinimpact"]),
    ("Netflix", "entertainment", [], ["netflix", "netflixmena"]),
    ("Disney+", "entertainment", ["Disney Plus"], ["disneyplus"]),
    ("Shahid", "entertainment", [], ["shahidvod"]),
    ("OSN", "entertainment", ["OSN+"], ["osn"]),
    ("Anghami", "entertainment", [], ["anghami"]),
    ("Twitch", "entertainment", [], ["twitch"]),
    # Telecom and automotive
    ("Etisalat", "telecom", ["e& UAE", "eand"], ["etisalat", "eand"]),
    ("du", "telecom", [], ["dutelecom"]),
    ("STC", "telecom", [], ["stc"]),
    ("Vodafone", "telecom", [], ["vodafone"]),
    ("Verizon", "telecom", [], ["verizon"]),
    ("T-Mobile", "telecom", ["T Mobile", "Tmobile"], ["tmobile"]),
    ("Tesla", "automotive", [], ["teslamotors", "tesla"]),
    ("Toyota", "automotive", [], ["toyota"]),
    ("BMW", "automotive", [], ["bmw"]),
    ("Mercedes-Benz", "automotive", ["Mercedes", "Merc"], ["mercedesbenz"]),
    ("Porsche", "automotive", [], ["porsche"]),
    ("Lexus", "automotive", [], ["lexus"]),
    ("Nissan", "automotive", ["Nissan Patrol"], ["nissan", "nissanmiddleeast"]),
    ("Land Rover", "automotive", ["Range Rover"], ["landrover", "rangerover"]),
    ("Kia", "automotive", [], ["kia"]),
    ("Hyundai", "automotive", [], ["hyundai"]),
]

# Names that are also ordinary words or fragments: a spoken match needs one of these context words nearby.
AMBIGUOUS = {
    "Apple": ["iphone", "macbook", "airpods", "apple watch", "ipad", "mac", "ios", "app store", "apple store"],
    "Target": ["target run", "target haul", "shop", "store", "aisle", "bought", "buy", "went to target", "at target"],
    "Amazon": ["order", "prime", "delivery", "bought", "buy", "haul", "link", "cart", "package"],
    "Dove": ["soap", "body wash", "deodorant", "shampoo", "conditioner", "skin"],
    "Coach": ["bag", "purse", "wallet", "outlet", "leather"],
    "Prime Hydration": ["drink", "bottle", "hydration", "flavor", "flavour", "energy"],
    "Monster Energy": ["drink", "can", "energy", "caffeine"],
    "Honey": ["extension", "coupon", "browser", "code", "checkout", "paypal"],
    "Calm": ["app", "meditation", "sleep", "subscription"],
    "Ritual": ["vitamins", "vitamin", "supplement", "multivitamin"],
    "Aura": ["app", "identity", "protection", "subscription", "antivirus"],
    "Steam": ["deck", "game", "games", "gaming", "pc", "library", "sale"],
    "Raid Shadow Legends": ["game", "download", "champions", "play"],
    "Ghost Lifestyle": ["protein", "energy", "pre workout", "preworkout", "supplement", "drink"],
    "Bloom Nutrition": ["greens", "supplement", "powder", "scoop", "drink"],
    "Magnum": ["ice cream", "chocolate", "almond", "dessert"],
    "Galaxy Chocolate": ["chocolate", "bar", "caramel", "smooth"],
    "Philadelphia": ["cream cheese", "cheesecake", "bagel", "spread"],
    "Factor": ["meals", "meal", "prep", "delivery", "code"],
    "Stanley": ["cup", "tumbler", "bottle", "quencher", "40 oz"],
    "Ridge Wallet": ["wallet", "carry", "cards"],
    "On Running": ["shoes", "running", "sneakers", "trainers", "cloud"],
    "Uber": ["ride", "driver", "car", "app", "trip", "airport"],
    "Noon": ["order", "app", "delivery", "sale", "yellow friday", "bought", "noon.com"],
    "Emirates": ["flight", "fly", "flew", "airline", "business class", "economy", "first class", "cabin"],
    "Wise": ["transfer", "account", "card", "money", "currency", "fees"],
    "Hers": ["forhers", "hair", "skin", "prescription", "treatment"],
    "Hims": ["hair", "skin", "prescription", "treatment", "forhims"],
    "du": ["sim", "network", "5g", "plan", "data", "telecom", "postpaid", "prepaid"],
    "Shahid": ["series", "watch", "stream", "episode", "vip"],
    "Pret": ["coffee", "sandwich", "subscription", "lunch"],
    "Subway": ["sandwich", "sandwiches", "footlong", "cookie", "lunch", "order"],
    "Kia": ["car", "drive", "suv", "sportage", "seltos", "ev"],
    "Sony": ["camera", "headphones", "tv", "playstation", "lens", "a7"],
    "Canon": ["camera", "lens", "shoot", "eos", "r5", "r6"],
    "Puma": ["shoes", "sneakers", "outfit", "trainers"],
    "Anua": ["serum", "toner", "skincare", "cleanser"],
    "Bubble Skincare": ["skincare", "moisturizer", "cleanser", "serum"],
    "Laneige": ["lip", "mask", "sleeping", "skincare", "cream"],
    # Place names, common words and first names that are also brands.
    "Jumeirah": ["hotel", "resort", "burj al arab", "staycation", "suite", "room", "madinat", "naseem", "al qasr", "mina a", "saray",
                 "saadiyat", "emirates towers", "beach hotel", "check in", "checked in", "jumeirahgroup"],
    "Hilton": ["hotel", "resort", "stay", "staycation", "suite", "room", "honors", "waldorf", "conrad", "doubletree", "hampton", "lobby", "pool"],
    "Marriott": ["hotel", "resort", "stay", "bonvoy", "suite", "room", "points", "lobby", "pool"],
    "Booking.com": ["booking.com", "hotel", "hotels", "stay", "trip", "genius", "bookingcom"],
    "Etihad": ["airways", "flight", "flights", "fly", "flew", "flying", "airline", "business class", "economy", "abu dhabi", "lounge"],
    "Visit Dubai": ["visitdubai", "visit.dubai", "dubai tourism", "dubai department"],
    "Visit Qatar": ["visitqatar", "qatar tourism"],
    "Saudi Tourism": ["visitsaudi", "saudi tourism", "saudi tourism authority"],
    "Beats": ["headphones", "earbuds", "buds", "dre", "studio", "solo", "pill", "powerbeats", "speaker", "noise cancel"],
    "Google Pixel": ["pixel 8", "pixel 9", "pixel 10", "phone", "camera", "google", "android", "fold"],
    "Celsius": ["drink", "can", "energy", "caffeine", "flavor", "flavour", "sip"],
    "Barbican": ["drink", "malt", "can", "bottle", "flavor", "flavour", "sip"],
    "Whoop": ["band", "strap", "recovery", "sleep", "wearable", "tracker", "hrv", "strain"],
    "Oura": ["ring", "sleep", "readiness", "score", "tracker", "hrv"],
    "Yeti": ["cooler", "tumbler", "cup", "bottle", "mug", "rambler"],
    "Brilliant": ["brilliant.org", "course", "courses", "lesson", "lessons", "math", "learn", "learning", "app", "interactive"],
    "Notion": ["template", "templates", "workspace", "database", "app", "notes", "planner", "dashboard", "page"],
    "Tabby": ["pay", "installment", "instalment", "installments", "instalments", "checkout", "split", "bnpl", "app", "cashback"],
    "Tamara": ["pay", "installment", "instalment", "installments", "instalments", "checkout", "split", "bnpl", "app"],
    "Twitch": ["stream", "streaming", "streamer", "live", "channel", "subs", "chat"],
    "Costa Coffee": ["coffee", "latte", "cappuccino", "cup", "drink", "barista", "iced", "frappe"],
    "Five Guys": ["burger", "burgers", "fries", "shake", "milkshake", "order", "eat", "ate", "eating", "food", "restaurant"],
    "Rhode": ["skin", "lip", "peptide", "gloss", "tint", "glazing", "blush", "hailey", "case", "barrier"],
    "Alo Yoga": ["yoga", "leggings", "set", "outfit", "wearing", "wear", "activewear", "hoodie", "workout"],
    "Pandora": ["charm", "charms", "bracelet", "jewelry", "jewellery", "ring", "necklace"],
    "The Ordinary": ["serum", "niacinamide", "glycolic", "retinol", "peeling", "skincare", "skin", "hyaluronic", "acid", "routine"],
    "Summer Fridays": ["lip", "balm", "butter", "mask", "skincare", "skin", "gloss", "tint"],
    "Benefit Cosmetics": ["mascara", "brow", "brows", "blush", "primer", "hoola", "porefessional", "roller lash", "gimme brow", "makeup",
                          "cosmetics"],
    "Tarte": ["shape tape", "concealer", "blush", "mascara", "maracuja", "makeup", "cosmetics", "bronzer"],
    "Revolve": ["dress", "outfit", "haul", "order", "ordered", "code", "festival", "clothes", "wearing"],
    "Kinder": ["bueno", "chocolate", "egg", "surprise", "joy", "snack", "sweet"],
    "Puck": ["cheese", "cream", "labneh", "spread", "sandwich", "recipe", "cooking"],
    "Lay's": ["chips", "crisps", "bag", "flavor", "flavour", "snack"],
    "Quaker": ["oats", "oatmeal", "porridge", "breakfast", "granola"],
    "Lulu Hypermarket": ["hypermarket", "grocery", "groceries", "supermarket", "shopping", "haul", "store", "aisle", "offer", "offers"],
    "Fitness First": ["gym", "class", "classes", "workout", "membership", "trainer", "training"],
    "Barry's": ["bootcamp", "class", "workout", "red room", "treadmill", "gym"],
}


def catalog():
    """Dictionary entries as {name, category, terms, handles, context} rows (terms = name + aliases)."""
    return [{"name": n, "category": c, "terms": [n, *a], "handles": [h.lower() for h in hs],
             "context": [w.lower() for w in AMBIGUOUS.get(n, [])]} for n, c, a, hs in BRANDS]
